import JSZip from "jszip";

export interface FileToZip {
  path: string;
  content: string;
}

export interface SupabaseCredentials {
  url: string;
  anonKey: string;
}

/**
 * Calculate the approximate byte size of a string (handles Unicode)
 */
export function getByteSize(str: string): number {
  return new Blob([str]).size;
}

/**
 * Format bytes to human readable string
 */
export function formatBytes(bytes: number): string {
  if (bytes === 0) return "0 B";
  const k = 1024;
  const sizes = ["B", "KB", "MB", "GB"];
  const i = Math.floor(Math.log(bytes) / Math.log(k));
  return `${parseFloat((bytes / Math.pow(k, i)).toFixed(1))} ${sizes[i]}`;
}

/**
 * Generate a README.md file with project information and setup instructions
 */
function generateReadme(appName: string, files: FileToZip[], hasSupabase: boolean): string {
  const fileList = files
    .map((f) => f.path)
    .sort()
    .map((p) => `- \`${p}\``)
    .join("\n");

  const supabaseStep = hasSupabase
    ? `
2. Supabase is pre-configured:
   - \`.env.local\` already contains your Supabase credentials
   - Run \`schema.sql\` against your Supabase database if you haven't already

3. Run the development server:
   \`\`\`bash
   npm run dev
   \`\`\``
    : `
2. Run the development server:
   \`\`\`bash
   npm run dev
   \`\`\``;

  return `# ${appName}

> Generated with [Promptly AI App Builder](https://promptly.app)

## Getting Started

1. Install dependencies:
   \`\`\`bash
   npm install
   \`\`\`
${supabaseStep}

${hasSupabase ? "4" : "3"}. Open [http://localhost:3000](http://localhost:3000) in your browser.

## Project Structure

${fileList}

## Tech Stack

- **Framework**: Next.js 16
- **Styling**: Tailwind CSS v4
- **Language**: TypeScript

## License

This project was generated by Promptly AI. Feel free to use, modify, and distribute.
`;
}

/**
 * Create a ZIP file from an array of files with folder structure
 * @param files Array of files with path and content
 * @param appName Name of the project (used for filename and README)
 * @returns Blob of the ZIP file
 */
export async function createProjectZip(
  files: FileToZip[],
  appName: string,
  supabaseCredentials?: SupabaseCredentials
): Promise<Blob> {
  const zip = new JSZip();

  // Add each file to the ZIP, preserving folder structure
  for (const file of files) {
    // JSZip handles nested paths automatically (e.g., "app/page.tsx")
    zip.file(file.path, file.content);
  }

  // Add .env.local with real Supabase credentials if provided
  if (supabaseCredentials) {
    const envLocal = `NEXT_PUBLIC_SUPABASE_URL=${supabaseCredentials.url}\nNEXT_PUBLIC_SUPABASE_ANON_KEY=${supabaseCredentials.anonKey}\n`;
    zip.file(".env.local", envLocal);
  }

  // Add generated README.md
  const readme = generateReadme(appName, files, !!supabaseCredentials);
  zip.file("README.md", readme);

  // Generate the ZIP blob
  const blob = await zip.generateAsync({
    type: "blob",
    compression: "DEFLATE",
    compressionOptions: { level: 6 },
  });

  return blob;
}

/**
 * Trigger browser download of a blob
 * @param blob The blob to download
 * @param filename The filename for the download
 */
export function downloadBlob(blob: Blob, filename: string): void {
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}

/**
 * Calculate total size of all files
 */
export function calculateTotalSize(files: FileToZip[]): number {
  return files.reduce((total, file) => total + getByteSize(file.content), 0);
}
