/**
 * Bundle Skills Script
 *
 * Reads all SKILL.md files at build time and generates a TypeScript module
 * with embedded skill data. This ensures skills are available in environments
 * where the filesystem `skills/` directory doesn't exist (e.g., Convex cloud).
 *
 * Run with: npx tsx scripts/bundle-skills.ts
 */

import fs from "fs/promises";
import path from "path";
import matter from "gray-matter";

const SKILLS_DIR = path.join(process.cwd(), "skills");
const OUTPUT_PATH = path.join(process.cwd(), "lib", "agents", "skills-bundle.ts");

interface BundledSkill {
  name: string;
  description: string;
  category: string;
  agents: string[];
  instructions: string;
}

/**
 * Recursively scan skills directory for SKILL.md files
 */
async function scanSkills(dir: string): Promise<BundledSkill[]> {
  const skills: BundledSkill[] = [];

  const entries = await fs.readdir(dir, { withFileTypes: true });

  for (const entry of entries) {
    if (!entry.isDirectory()) continue;

    const skillPath = path.join(dir, entry.name, "SKILL.md");

    try {
      const fileContent = await fs.readFile(skillPath, "utf-8");
      const { data, content } = matter(fileContent);

      if (data.name && data.description) {
        skills.push({
          name: data.name,
          description: data.description,
          category: data.category || "general",
          agents: data.agents || ["all"],
          instructions: content.trim(),
        });
      }
    } catch {
      // Not a skill directory, recurse into subdirectory
      const subSkills = await scanSkills(path.join(dir, entry.name));
      skills.push(...subSkills);
    }
  }

  return skills;
}

async function main() {
  console.log("[bundle-skills] Scanning skills directory...");

  const skills = await scanSkills(SKILLS_DIR);
  skills.sort((a, b) => a.name.localeCompare(b.name));

  console.log(`[bundle-skills] Found ${skills.length} skills:`);
  for (const skill of skills) {
    console.log(`  - ${skill.name} (${skill.category})`);
  }

  // Generate TypeScript module
  const bundleEntries = skills.map((skill) => {
    return `  ${JSON.stringify(skill.name)}: {
    name: ${JSON.stringify(skill.name)},
    description: ${JSON.stringify(skill.description)},
    category: ${JSON.stringify(skill.category)},
    agents: ${JSON.stringify(skill.agents)},
    instructions: ${JSON.stringify(skill.instructions)},
  }`;
  });

  const output = `/**
 * Auto-generated skills bundle — DO NOT EDIT MANUALLY
 *
 * Generated by: npx tsx scripts/bundle-skills.ts
 * Generated at: ${new Date().toISOString()}
 * Skills count: ${skills.length}
 *
 * This file embeds all SKILL.md content so skills are available
 * in environments without filesystem access (e.g., Convex cloud).
 */

export interface BundledSkill {
  name: string;
  description: string;
  category: string;
  agents: string[];
  instructions: string;
}

export const SKILLS_BUNDLE: Record<string, BundledSkill> = {
${bundleEntries.join(",\n")}
};
`;

  await fs.writeFile(OUTPUT_PATH, output, "utf-8");

  console.log(`\n[bundle-skills] Generated ${OUTPUT_PATH}`);
  console.log(`[bundle-skills] Bundle size: ${(Buffer.byteLength(output) / 1024).toFixed(1)} KB`);
  console.log(`[bundle-skills] Total skills: ${skills.length}`);
}

main().catch((err) => {
  console.error("[bundle-skills] Failed:", err);
  process.exit(1);
});
